apiVersion: v1
kind: Pod
metadata:
  name: python-microservice
  namespace: tech.prod
  labels:
    app: python-microservice
spec:
  containers:
  - name: python-microservice
    image: python-microservice:latest
    resources:
      limits:
        memory: "3Gi"
    ports:
    - containerPort: 8000
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: python-microservice-service
  namespace: tech.prod
spec:
  selector:
    app: python-microservice
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
